- name: Add kubernetes repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install packages
  yum: name={{ packages }} state=present

- name: Enable and Start kubelet
  service:
    name: kubelet
    enabled: yes
    state: started
