- name: Install Packages
  yum: name={{ packages }} state=present 


# TODO: do not stop firewall and enable only needed set of ports
- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no


