--

- name: Install Packages
  yum: name={{ item }} state=present 
  with_items: "{{ packages }}"

- name: Enable and Start Docker
  service:
    name: docker
    state: started
    enable: yes

# TODO: do not stop firewall and enable only needed set of ports
- name: Disable firewall
  service:
    name: firewalld
    state: stopped
    enable: no


