- name: Add docker repository
  yum_repository:
    name: docker-ce
    description: docker-ce
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

# TODO: add version
- name: Install Docker CE
  yum:
    name: docker-ce
    state: present

- name: Enable and Start Docker
  service:
    name: docker
    state: started
    enabled: yes

